
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("794x489")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 489,
    width = 794,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    794.0,
    489.0,
    fill="#000000",
    outline="")

canvas.create_text(
    147.0,
    123.0,
    anchor="nw",
    text=" Part Replacement",
    fill="#1E1E1E",
    font=("Inter Medium", 40 * -1)
)

canvas.create_text(
    138.0,
    207.0,
    anchor="nw",
    text="Load ABM *",
    fill="#1E1E1E",
    font=("Inter Medium", 20 * -1)
)

canvas.create_text(
    138.0,
    300.0,
    anchor="nw",
    text="Load page & line *",
    fill="#1E1E1E",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    431.0,
    206.0,
    anchor="nw",
    text="Select working directory *",
    fill="#1E1E1E",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    431.0,
    304.0,
    anchor="nw",
    text="Enable Debug",
    fill="#1E1E1E",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    266.0,
    44.0,
    539.0,
    153.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    245.0,
    74.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=574.0,
    y=307.0,
    width=76.0,
    height=32.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=672.0,
    y=75.0,
    width=76.0,
    height=32.0
)

canvas.create_rectangle(
    662.0,
    29.0,
    758.0,
    51.0,
    fill="#000000",
    outline="")

canvas.create_text(
    662.0,
    26.0,
    anchor="nw",
    text="Date",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=431.0,
    y=237.0,
    width=70.0,
    height=22.0
)

canvas.create_text(
    438.0,
    235.0,
    anchor="nw",
    text="Browse",
    fill="#000000",
    font=("Inter", 16 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=138.0,
    y=237.0,
    width=70.0,
    height=22.0
)

canvas.create_text(
    145.0,
    235.0,
    anchor="nw",
    text="Browse",
    fill="#000000",
    font=("Inter", 16 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=138.0,
    y=332.0,
    width=70.0,
    height=22.0
)

canvas.create_text(
    145.0,
    330.0,
    anchor="nw",
    text="Browse",
    fill="#000000",
    font=("Inter", 16 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=307.0,
    y=389.0,
    width=179.0,
    height=57.0
)
window.resizable(False, False)
window.mainloop()
